### ISSUE TITLE
"pre" and "post" task tasks

### ISSUE THREAD

**Issue by Zerogiven** [kentcdodds/nps#167] opened 2018-01-16 06:37 UTC
I would love to have automatic pre and post executions like npm script have. There you can prefix all tasks with "pre" or "post". At nps one solution would be also check if prefixed tasks are available. The other one which i like a bit more would be to check if package-scripts have a root element called "_pre" and "_post" or "pre" and "post".

For example:

```javascript
module.exports = {
  test: "jest",
  pre: {
    test: "tslint"
  }
}
```

```console
nps test
```

Executes for the above example the following:

```console
nps pre.test && jest
```
I think this could be easily done, just want to ask if you're interested in a PR?

**Comment by kentcdodds** [comment] 2018-01-16 06:40
Hey @Zerogiven :wave:

This is a duplicate of https://github.com/kentcdodds/nps/issues/67

Please see that issue for more info. Thanks!

**Closed by kentcdodds** 2018-01-16 06:40 UTC
